# This expects a few things
#
# - ag for searching (https://github.com/ggreer/the_silver_searcher)
# - ctags for well tags (https://github.com/universal-ctags/ctags)
# - gocode for code completion (https://github.com/nsf/gocode)
# - goimports for code formatting on save (https://golang.org/x/tools/cmd/goimports)
# - gogetdoc for documentation display and source jump (https://github.com/zmb3/gogetdoc)
# - jq for json deserializaton, required by gogetdoc
 
hook global InsertCompletionHide .* %{
	unmap window insert <tab> <c-n>
	unmap window insert <backtab> <c-p>
}
hook global InsertCompletionShow .* %{
	map window insert <tab> <c-n>
	map window insert <backtab> <c-p>
}
hook global WinCreate .* %{
	add-highlighter number_lines -hlcursor
	add-highlighter show_matching
	# default space char doesn't show 
	add-highlighter show_whitespaces -spc \  -nbsp ∙
	add-highlighter wrap -word
}
hook global WinSetOption filetype=go %{
	go-enable-autocomplete
	set window indentwidth 0 # 0 means real tab
	set window formatcmd 'goimports'
	set window lintcmd 'gometalinter .'
	set window makecmd 'go install -v -u .'
	map window normal G :go-jump<ret>
}

set global grepcmd 'ag --column'
set global ui_options ncurses_assistant=none:ncurses_enable_mouse=true
set global indentwidth 4
set global scrolloff 5,5

def find -params 1 -shell-candidates %{ ag --nocolor --ignore=vendor --ignore images --ignore svg --ignore fonts -g "" } %{ edit %arg{1} }
def git-edit -params 1 -shell-candidates %{ git ls-files } %{ edit %arg{1} } -docstring "Uses git ls-files to find files"
def qa q -docstring "stop using this (muscle memory too strong)"

alias global ge git-edit
alias global f find
alias global bd delete-buffer
alias global qa quit
alias global wq write-quit
alias global qa! quit!
alias global wq! write-quit!
alias global wqa write-all-quit
alias global wqa! write-all-quit

map global normal -- - %{:find <tab>}
map global user c %{: comment-line<ret>} -docstring "Comment or uncomment selected lines"
map global user p %{|nc termbin.com 9999<ret>xyuP<a-;>k,c} -docstring "Publish to termbin.com"
map global user t %{: nop %sh{tmux selectp -t +1}<ret>} -docstring "Switch to next tmux window"
map global user T %{: nop %sh{tmux split -v -p 20\; last-pane}<ret>} -docstring "Create new tmux window below"
map global user r %{: prompt %{Run:} %{echo %sh{tmux send-keys -t +1 "$kak_text" Enter }}<ret>} -docstring "Run command in next tmux window"

colorscheme nofrils-acme
try %{ source .kakrc.local }
