hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <backtab> <c-p> }
hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <backtab> <c-p> }

hook global WinCreate .* %{ add-highlighter number_lines -relative -hlcursor }
hook global WinCreate .* %{ add-highlighter show_matching }
hook global WinCreate .* %{ add-highlighter show_whitespaces }
hook global WinCreate .* %{ add-highlighter wrap }

hook -group TrailingWhitespaces global WinCreate .* %{ add-highighter regex '\h+$' 0:default,red }

set global ui_options ncurses_assistant=none
set global indentwidth 4

hook global WinSetOption filetype=(c|cpp) %{
    clang-enable-autocomplete 
    clang-enable-diagnostics
    alias window lint clang-parse
    alias window lint-next clang-diagnostics-next
}

hook global WinSetOption filetype=python %{
    jedi-enable-autocomplete
    flake8-enable-diagnostics
    alias window lint flake8-lint
    alias window lint-next flake8-diagnostics-next
}

hook global WinSetOption filetype=go %{
    set buffer indentwidth 0 # 0 means real tab
    go-enable-autocomplete
    map buffer normal G :go-jump<CR>
}

# XXX: 
def find -params 1 -shell-candidates %{ find . -type f } %{ edit %arg{1} }
colorscheme acme
